### PR TITLE
misstyped element in the example div.

### PR DESCRIPTION
**Pull request by meldaravaniel**

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for spotting that, you're right. We are using an `id` in this example, not a `class`.

**Comment by AMBudnik** [comment]
Sorry, but it looks like we do not have a CLA signed by you @meldaravaniel 
Could you sign it, please? Only then we will be able to pull the changes.

**Comment by meldaravaniel** [comment]
@AMBudnik My bad!  Signed.

**Comment by AMBudnik** [comment]
Thank you @meldaravaniel :)

**Pull request merged**
